### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by nyukers** [imb101/ComfyUI-FaceSwap#3]
It's a shame, but the code doesn't work, even in your example with your photo the same error - **list index out of range**.(((
File "C:\SDComfyUI\ComfyUI\custom_nodes\ComfyUI-FaceSwap\FaceSwapNode.py", line 52

**Comment by mazihan723** [comment]
same error, why

**Comment by nyukers** [comment]
> same error, why

ok, never mind, I will go to ReActor

**Comment by chowii** [comment]
well if its not fixed or no documentation what the cause is and how to avoid it, might as well not use it :(
